---
title: "homework0"
output: html_document
date: "2022-08-30"
---

You have completed DataCamp exercises and learned data structures such as vectors, matrices, lists and dataframes. In this exercise, you are going to test yourself what you have learned.

This dataset was collected between the 20th of January and the 1st of June 2020. The purpose is to build your skills and understanding of the data analysis workflow by evaluating the COVID-19 situation through this dataset. 

Our analysis tries to provide an answer to this question: **Which countries have had the highest number of positive cases against the number of tests?**

The dataset of our study contains daily & cumulative number of COVID-19 tests conducted, number of positive, hospitalized, recovered & death cases reported by country. In details here are the columns in the dataset:

1. <code>Date</code>: Date
2. <code>Continent_Name</code>: Continent names
3. <code>Two_Letter_Country_Code</code>: Country codes
4. <code>Country_Region</code>: Country names
5. <code>Province_State</code>: States/province names; value is <code>All States</code> when state/provincial level data is not available
6. <code>positive</code>: Cumulative number of positive cases reported.
7. <code>active</code>: Number of active cases on that day.
8. <code>hospitalized</code>: Cumulative number of hospitalized cases reported.
9. <code>hospitalizedCurr</code>: Number of actively hospitalized cases on that day.
10. <code>recovered</code>: Cumulative number of recovered cases reported.
11. <code>death</code>: Cumulative number of deaths reported.
12. <code>total_tested</code>: Cumulative number of tests conducted.
13. <code>daily_tested</code>: Number of tests conducted on the day; if daily data is unavailable, daily tested is averaged across number of days in between.
14. <code>daily_positive</code>: Number of positive cases reported on the day; if daily data is unavailable, daily positive is averaged across number of days in.
