---
title: "report"
author: "Jenny W"
date: "2022-11-12"
output: html_document
---

```{r}
library("tidyverse")
library("readr")
Places <- read_csv("C:\\Users\\26292\\Downloads\\safegraph_data_purchase_sep-14-2022\\your_data_sep_14_2022_0631pm.csv.gz")
dim(Places)
Patterns <- read_csv("C:\\Users\\26292\\Downloads\\safegraph_data_purchase_sep-18-2022\\your_data_sep_18_2022_0306pm.csv.gz")
dim(Patterns)
df <- left_join(Patterns, Places, by = "placekey")
head(df)
```


```{r}
# the number of na in naics column in places dataset
nacount <- Places[is.na(Places$naics_code),]

# the number of na in naics column in df
nacount2 <- df[is.na(df$naics_code),]

```



```{r}
library(tidyverse)
df_filter<- subset(df, naics_code==722513)
head(df_filter)

count<-df_filter %>% group_by(location_name.x)%>%count()%>%arrange(n)
view(count)

lessthan10 <-count %>% filter(n<10)
lessthan10
tentotwenty <-count %>% filter(n>=10 & n<20)
tentotwenty
twentytothirty <-count %>% filter(n>=20 & n<30)
twentytothirty
thirtytoforty <-count %>% filter(n>=30 & n<40)
thirtytoforty
fortytofifty <-count %>% filter(n>=40 & n<50)
fortytofifty
fiftytosixty <-count %>% filter(n>=50 & n<60)
fiftytosixty
sixtytoseventy <-count %>% filter(n>=60 & n<=70)
sixtytoseventy
```
```{r}
library(tidyverse)
counttt<-df_filter %>%
  group_by(location_name.x) %>%
  count()
view(counttt)
  
```

```{r}

count1 <- df_filter %>% 
  group_by(location_name.x, street_address.x) %>%
  count()
view(count1)
count2<-count1 %>%
  group_by(location_name.x) %>%
  count()
view(count2)

traffic_morechain<-count2 %>%
  filter(n>4)
traffic_lesschain<-count2 %>%
  filter(n<=4)

df_m<-inner_join(df_filter,traffic_morechain,by="location_name.x")
#>=5 stores
dfm_visitors<-df_m %>%
  select(location_name.x,street_address.x,postal_code.x,raw_visitor_counts,latitude,longitude) %>%
  group_by(street_address.x) %>%
  summarize(n=sum(raw_visitor_counts))
view(dfm_visitors)
convenient<-df_m %>%
  select(location_name.x,street_address.x,latitude,longitude)
dfm_final<-left_join(convenient,dfm_visitors,by='street_address.x') 
dfm_final<-dfm_final[!duplicated(dfm_final),]
view(dfm_final)

df_l<-inner_join(df_filter,traffic_lesschain,by="location_name.x")
#<5 stores
dfl_visitors<-df_l %>%
  select(location_name.x,street_address.x,postal_code.x,raw_visitor_counts,latitude,longitude) %>%
  group_by(street_address.x) %>%
  summarize(n=sum(raw_visitor_counts))
convenient<-df_l %>%
  select(location_name.x,street_address.x,latitude,longitude)
dfl_final<-left_join(convenient,dfl_visitors,by='street_address.x') 
dfl_final<-dfl_final[!duplicated(dfl_final),]
view(dfl_final)

```

```{r}
library(ggplot2)
library(ggthemes)
library(ggrepel)
mean(dfm_final$n) #2047-1 3836-4
mean(dfl_final$n) #1997-1 1739-4
(3836+1739)/2 #2788
p_dfm1<-ggplot(data=dfm_final,aes(x=longitude,y=latitude))+geom_point(color='gray50')+xlim(-71.18,-71)+ylim(42.27,42.39)
p_dfm2=p_dfm1+geom_point(data=subset(dfm_final,n>=2788),mapping=aes(x=longitude,y=latitude,color='red'))+labs(title='Group 1: # of store>4',x='latitude',y='longitude',color='>#avg in-store traffic')
print(p_dfm2)

p_dfl1<-ggplot(data=dfl_final,aes(x=longitude,y=latitude))+geom_point(color='gray50')+xlim(-71.18,-71)+ylim(42.27,42.39)
p_dfl2=p_dfl1+geom_point(data=subset(dfl_final,n>=2788),mapping=aes(x=longitude,y=latitude,color='red'))+labs(title='Group2 & Group3: # of stores <=4',x='latitude',y='longitude',color='>#avg in-store traffic')
print(p_dfl2)

```