---
title: "Homework 3"
author: "Yeabin Moon"
date: "2022-09-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Homework 3

You must review lecture 9 before working on this homework.

We worked on cleaning six dataframes containing data on New York City high school test scores, demographics, and school locations in the previous lesson. We used tools for dataframe manipulation to remove data that we won't need for our analysis, create new variables, and change data types.

In this homework, we'll learn about efficiently organizing data and how to use string manipulation techniques to finish cleaning the data.

You have 6 data sets: 
```
sat_results_1.csv
ap_2010_1.csv
class_size_1.csv
demographics_1.csv
graduation_1.csv
hs_directory_1.csv
```
### Question 1
<b>Import the sat_results_1.csv, ap_2010_1.csv, class_size_1.csv, demographics_1.csv, graduation_1.csv, and hs_directory_1.csv files into R as dataframes with the following names using the read_csv() function:</b>
```
sat_results
ap_2010
class_size
demographics
graduation
hs_directory
```

We'll finish cleaning the six dataframes. We'll also discuss an important aspect of data cleaning: Structuring data so that it is optimally organized for analysis. Hadley Wickham, a chief scientist at RStudio and the creator of the tidyverse, coined the concept of "tidy data" to describe the organization principles. They optimize our ability to make sense of data and analyze it using popular tidyverse tools.

According to the tidy data concept, for a dataset to be tidy:

- Each variable must have its own column
- Each observation must have its own row
- Each value must have its own cell

Most R functions (in base R as well as the tidyverse) work best with data where variables are placed in columns. This is because R is written to work with vectors of values. Real-world data often violate the tidy data principles. Use head() for each dataframe and see whether it is tidy.

Let's have a look at the <em>graduation</em> dataframe. Now, we need to change the data type of values of the Total Grads - % of cohort and Dropped Out - % of cohort variables from character to numeric. Notice that the values of these variables are all followed by a % symbol. As a result, instead of using as.numeric() to change the data type, we will need to extract only the character strings' numeric portion. We can parse each string, or subset it into its different data types, using a handy function from the readr package: parse_number(). The parse_number() function takes a vector as input and drops any characters before or after the first number in strings.

To extract numbers from strings for multiple variables at once using parse_number(), we can use the mutate() and across() functions as we did to change data type from character to numeric in the lecture 9. Specify the range of columns we want to transform, and apply the parse_number() function to those columns' values:
```
data_frame %>%
    mutate(across(`first column in range`:`last column in range`, parse_number))
```

### Question 2
<b>Create a new graduation dataframe in which all values of the following variables consist of numeric data</b>
```
Total Grads - % of cohort
Dropped Out - % of cohort
```
Remember that warning messages alerting you to parsing failures are to be expected when there are non-numeric values of the variable you are passing to parse_number(). Don't worry about this warning message for now.

Now, the variables Total Grads - % of cohort and Dropped Out - % of cohort variables in the graduation dataframe consist of numeric data. Now let's see <em>hs_directory</em> dataset.

The Location 1 variable of the hs_directory dataset is untidy because it contains several elements in the same variable. Actually, the Location 1 variable contains useful information for looking at spatial patterns in the data: The latitude and longitude, collectively known as the geographic coordinates, of each school. For each value of Location 1, coordinates are contained within a lengthy character string. We'll need to isolate and use them to visualize spatial trends in the future. 

To create maps using the NYC schools data, we will need to extract information from Location 1 to create two new variables: one for latitude and one for longitude.

Within each value of Location 1, there are two instances of the character sequence \n. Splitting the string at \n will result in three strings for each value of Location 1. Look at the tidyr function, separate() 
```
library(tidyr)

dataframe %>%
    separate(col = the_name_of_the_column_to_separate,
           into = c("string_1", "string_2", "string_3"), # the names of new columns
           sep = "\n") # the separator of string
```

### Question 3
<b>Create a new hs_directory dataframe containing a new variable column, lat_long, containing the coordinates (surrounded by parentheses) extracted from the Location 1 column</b>

- Use the separate() function to split the column Location 1 into three new columns: "string_1", "string_2", and "string_3" with "\n" as separator.
- Use the select() function to remove the columns string_1 and string_2 because we don't need them.
- Use the rename() function to rename the string_3 column into lat_long

We now have a new column in hs_directory, lat_long, containing the latitude and longitude for each school. However, we need latitude and longitude to be split into separate variables. This way, when we're ready to create spatial visualizations, our data will be in the correct format for working with other R data visualization packages.

In the lat_long variable, they used a <b>comma</b> to separate the latitude and longitude. We can once again use the separate() function to split lat_long at the comma.

### Question 4
<b>Create a new hs_directory dataframe containing new columns, lat and long, containing the coordinates extracted from the lat_long column.</b>

- Use the separate() function to split the column lat_long into two new columns: "lat" and "long" with "," as the separator.

We have now extracted the latitude and longitude coordinates from Location 1 and created two new variables, lat and long, in the hs_directory dataframe. We aren't quite finished cleaning the latitude and longitude data, though. Although each column now contains its own variable, the strings still contain non-numeric characters (the parentheses) that will later present a problem when we want to transform the data type to numeric. Note that we want to retain the - in the longitude column. Negative longitudes denote geographic locations in the Earth's western hemisphere.

### Question 5
<b>Use str_sub() and mutate() to create a new hs_directory dataframe with lat and long variables containing only numeric characters.</b>

- Also, convert the data type of the lat and long variables from character to numeric.
- For this exercise, we can also use parse_number() to achieve the same result.

Now let's look at <em>class_size</em> data. This dataframe is nearly ready for analysis, but there's one more step we'll need to complete: Creating a DBN variable that we can use as a key to join the dataframes in the next. We can observe that the DBN variable in the other dataframes appears to be a combination of CSD and SCHOOL CODE. So we retained those variables in the summarized class_size dataframe. We can confirm this by comparing the CSD and SCHOOL CODE values for a few high schools in the class_size dataframe with the DBN of those high schools in the sat_results or ap_2010 dataframes.

To combine CSD and SCHOOL CODE into a new DBN variable, we will use concatenation and padding techniques. Let's think through the steps we'll need to take. Compare the formats of CSD and SCHOOL CODE in the class_size dataframe and DBN in the sat_results dataframe. We can begin by creating a new variable, DBN, in the class_size dataframe by combining CSD and SCHOOL CODE. Notice that the sat_results DBN values all have six digits -- there is a zero at the beginning of the number.

### Question 6
<b>Create a new DBN variable in the class_size dataframe.</b>

- Combine the columns CSD and SCHOOL CODE and assign the result to a new column DBN.
- Update the DBN column making sure that its values have six characters.