---
title: "homework1"
output: html_document
date: "2022-09-05"
---
# Part I

#### Q1.1 In homework 0, we examined the following question: <b>Which countries have had the highest number of positive cases against the number of tests?</b> In what settings could we conclude that this question is unanswerable?

#### Q1.2 What is the smallest value of *n* such that an algorithm whose running time is $100n^2$ runs faster than an algorithm whose running time is $2^n$ on the same machine? Use R to calcuate your answer.

#### Q1.3 Other than speed, what other measures of algorithm efficiency might you need to consider in a real-world setting?


# Part II

Part II sets the tone for your final project. For this exercise, you will work with <b>Places</b>. It consists of three files. README.txt, brand_info.csv, your_data_***.csv.gz. In general, data packages contain README files for a data guide, but the information here is partial. See the data descriptions from the following <a href="https://docs.safegraph.com/docs/places" target="_blank">Link</a>.

#### Q2.1. Describe in words what these two data sets present.


#### Q2.2. Why does <em>brand_info.csv</em> include fewer observations?

#### Q2.3 Which location (postal code) has the largest number of POIs? 

#### Q2.4 Postal-code location may cover too small area for spatial analysis. The data set has longitude, latitude, street address, city, and state geographical information. You may need to transform (or merge) the existing geo code to a common set of geographical units (See [Link](https://www.huduser.gov/portal/datasets/usps_crosswalk.html) for reference). Describe your strategy (you don't need to show your code.)



#### Q2.5: You may want to classify POIs in Boston by industry type. Columns *top_category*, and *naics_code* look fit. (See  [Link](https://www.census.gov/naics/reference_files_tools/2022_NAICS_Manual.pdf) for NAICS explanations). Describe what these two columns represent in your words.

#### Q2.6 Present the number of POIs by *top_category*.

#### Q2.7 Present the number of POIs by the first two leading digits in *naics_code*.

#### Q2.8 Suppose you want to research POIs in Boston by the first two leading digits in *naics_code*. You might notice that the number of POIs in the bottom eight industries are too low compared to the top six. Describe how you manage data and approach research in words.
