---
title: "Foundation Presentation"
author: "Group 4"
date: "2022-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
places <- read_csv("your_data_sep_10_2022_1100pm.csv", show_col_types = FALSE)
patterns <- read_csv("your_data_sep_17_2022_0143am.csv", show_col_types = FALSE)
df <- left_join(select(places, c(placekey,naics_code, sub_category)), 
                select(patterns,c(placekey, location_name, street_address, postal_code, brands, date_range_start, date_range_end, raw_visit_counts)), 
                by = "placekey") %>% filter(naics_code == '722511'|naics_code == '722513')
df
```
```{r}
df_na <- df %>% filter(is.na(location_name))
df_na
```
```{r}
df <- df %>% drop_na(location_name)
df
```

```{r}
monthly_visiting_num <- df %>% group_by(placekey, naics_code, category = sub_category, location_name, street_address, date_range_end) %>% summarise(month = as.numeric(format(date_range_end, format = "%m")) - 1, visiting = raw_visit_counts) %>% arrange(desc(visiting))
monthly_visiting_num
```

```{r}
full_service_monthly_visiting_num <- monthly_visiting_num %>% filter(naics_code == '722511') %>% filter(visiting > 60) %>% filter(visiting < 2000)
full_service_monthly_visiting_num
```
```{r}
ggplot(full_service_monthly_visiting_num, aes(x=visiting)) + geom_histogram(binwidth=5)
```


```{r}
limited_service_monthly_visiting_num <- monthly_visiting_num %>% filter(naics_code == '722513') %>% filter(visiting > 60) %>% filter(visiting < 2500)
limited_service_monthly_visiting_num
```
```{r}
ggplot(limited_service_monthly_visiting_num, aes(x=visiting)) + geom_histogram(binwidth=5)
```
```{r}
filtered_df <- merge(full_service_monthly_visiting_num, limited_service_monthly_visiting_num, all = TRUE) %>% arrange(desc(visiting)) %>% select(month, category, placekey, location_name, visiting)
head(filtered_df)
```
```{r}
top_1_in_each_month <- filtered_df %>% group_by(month) %>% summarize(max_visiting = max(visiting))
top_stores <- filter(filtered_df, visiting %in% top_1_in_each_month$max_visiting) %>% arrange(month)
top_stores
```


```{r}
top_1_popular_locations <- filtered_df %>% filter(placekey %in% top_stores$placekey)
top_1_popular_locations
```
```{r}
ggplot(top_1_popular_locations, aes(x = month, y = visiting, colour = location_name, group = location_name)) +
  geom_line()
```
```{r}
categorical_monthly_visiting_pattern <- filtered_df %>% group_by(category, month) %>% summarize(total_visiting = sum(visiting))
categorical_monthly_visiting_pattern
```
```{r}
ggplot(categorical_monthly_visiting_pattern, aes(x = month, y = total_visiting, colour = category, group = category)) +
  geom_line()
```

```{r}
total_visiting_counts <- filtered_df %>% group_by(month) %>% summarize(total_visiting = sum(visiting))
total_visiting_counts
```
```{r}
ggplot(total_visiting_counts, aes(x=month, y=total_visiting)) + 
  geom_bar(stat = "identity")
```

```{r}
all_time_locational_visiting <- monthly_visiting_num %>% group_by(location_name, placekey) %>% summarize(visiting = sum(visiting))
store_num_pattern <- all_time_locational_visiting %>% count(location_name, sort = T)
store_num_pattern
```

```{r}
ggplot(store_num_pattern, aes(x=n)) + geom_histogram(binwidth=1)
```
```{r}
independant <- store_num_pattern %>% filter(n == 1)
chain <- store_num_pattern %>% filter(n > 1)

independant_store <- dplyr::filter(filtered_df, location_name %in% independant$location_name) %>% group_by(month) %>% summarize(total_visiting = sum(visiting)) %>% mutate(type = "independant")
chain_store <- dplyr::filter(filtered_df, location_name %in% chain$location_name) %>% group_by(month) %>% summarize(total_visiting = sum(visiting)) %>% mutate(type = "chain")

all_stores <- merge(independant_store, chain_store, all = TRUE)
all_stores
```

```{r}
ggplot(all_stores, aes(x = month, y = total_visiting, colour = type, group = type)) +
  geom_line() +
  scale_color_manual(values=c('Purple','Brown'))
```

```{r}
Mcdonalds_Chipotle <- filtered_df %>% filter(location_name == "McDonald's" | location_name == "Chipotle Mexican Grill") %>% group_by(location_name, month) %>% summarize(total_visits = sum(visiting)) %>% arrange(desc(total_visits))
Mcdonalds_Chipotle
```
```{r}
ggplot(Mcdonalds_Chipotle, aes(x = month, y = total_visits, colour = location_name, group = location_name)) +
  geom_line() +
  scale_color_manual(values=c('#AC2318','#FFC72C'))
```
